# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/db77ca32-2a7e-4262-b3df-996c8030fa76";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-cffdcebe-8e81-48c5-946e-868db7b8468f".device = "/dev/disk/by-uuid/cffdcebe-8e81-48c5-946e-868db7b8468f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C0B2-C9DF";
      fsType = "vfat";
    };
  
  filesystems."/mnt/internalData" = 
    { device = "/dev/disk/by-uuid/701d0b93-031e-431d-aef4-cfd792f520f0";
      fsType = "xfs";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/22e1c420-d981-4771-a714-0f8f22b786ef"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
